/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedFlowsRouteImport } from './routes/_authenticated/flows'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPushRouteImport } from './routes/_authenticated/push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlowsRoute = AuthenticatedFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPushRoute = AuthenticatedPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/push': typeof AuthenticatedPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/push': typeof AuthenticatedPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/flows': typeof AuthenticatedFlowsRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/push': typeof AuthenticatedPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/campaigns'
    | '/flows'
    | '/loyalty'
    | '/overview'
    | '/push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/campaigns'
    | '/flows'
    | '/loyalty'
    | '/overview'
    | '/push'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/campaigns'
    | '/_authenticated/flows'
    | '/_authenticated/loyalty'
    | '/_authenticated/overview'
    | '/_authenticated/push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flows': {
      id: '/_authenticated/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AuthenticatedFlowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/push': {
      id: '/_authenticated/push'
      path: '/push'
      fullPath: '/push'
      preLoaderRoute: typeof AuthenticatedPushRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedFlowsRoute: typeof AuthenticatedFlowsRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPushRoute: typeof AuthenticatedPushRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedFlowsRoute: AuthenticatedFlowsRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPushRoute: AuthenticatedPushRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
